#!/usr/bin/env python3
"""Generate the app icon (gradient aperture on dark) for Android and iOS.

Usage (from app_flutter/):  python3 tool/gen_app_icon.py
Needs Pillow and numpy. The source is design-system/brand/logo-source.png: a
1254 x 1254 render of the aperture on a dark rounded square. Only the aperture
is lifted out (alpha from brightness), then re-composed on each target canvas,
so every size gets a clean background and the right safe-zone margin.
"""
import json
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
BRAND = ROOT.parent / "design-system" / "brand"
SOURCE = BRAND / "logo-source.png"

# Aperture circle in the source, measured from its coloured strokes.
CENTER = (624, 618)
RADIUS = 445
PAD = 12            # keep the anti-aliased rim

# Background gradient sampled from the source's rounded square (top -> bottom).
BG_TOP = (0x1B, 0x1B, 0x20)
BG_BOTTOM = (0x05, 0x05, 0x08)

# Aperture diameter as a share of the canvas.
FULL_BLEED = 0.72   # iOS and legacy Android icons
ADAPTIVE = 0.54     # adaptive foreground: inside the 66/108 safe circle


def aperture() -> Image.Image:
    """The aperture strokes on transparency, cropped to a square around the circle."""
    cx, cy = CENTER
    r = RADIUS + PAD
    src = Image.open(SOURCE).convert("RGB").crop((cx - r, cy - r, cx + r, cy + r))
    rgb = np.asarray(src).astype(np.float32)
    # The interior is near black (~5); strokes reach full brightness.
    alpha = np.clip((rgb.max(axis=2) - 14) / 170, 0, 1)
    # Un-premultiply against black so edges keep their hue when re-composed.
    colour = np.clip(rgb / np.maximum(alpha, 1e-3)[..., None], 0, 255)
    out = np.dstack([colour, alpha * 255]).astype(np.uint8)
    # Nothing outside the circle (drops the source's rounded-square edge).
    img = Image.fromarray(out, "RGBA")
    mask = Image.new("L", img.size, 0)
    ImageDraw.Draw(mask).ellipse((0, 0, img.width - 1, img.height - 1), fill=255)
    img.putalpha(Image.fromarray(np.minimum(np.asarray(img.getchannel("A")), np.asarray(mask))))
    return img


def gradient(size: int) -> Image.Image:
    t = np.linspace(0, 1, size, dtype=np.float32)[:, None, None]
    rows = np.array(BG_TOP, np.float32) * (1 - t) + np.array(BG_BOTTOM, np.float32) * t
    return Image.fromarray(np.repeat(rows, size, axis=1).astype(np.uint8), "RGB").convert("RGBA")


def place(art: Image.Image, size: int, share: float, canvas: Image.Image) -> Image.Image:
    d = round(size * share * (RADIUS + PAD) / RADIUS)
    a = art.resize((d, d), Image.LANCZOS)
    canvas.alpha_composite(a, ((size - d) // 2, (size - d) // 2))
    return canvas


def full_icon(art: Image.Image, size: int, rounded: bool = False) -> Image.Image:
    img = place(art, size, FULL_BLEED, gradient(size))
    if rounded:
        mask = Image.new("L", (size * 4, size * 4), 0)
        ImageDraw.Draw(mask).rounded_rectangle((0, 0, size * 4 - 1, size * 4 - 1),
                                               radius=int(size * 4 * 0.22), fill=255)
        img.putalpha(mask.resize((size, size), Image.LANCZOS))
    return img


def foreground(art: Image.Image, size: int, mono: bool = False) -> Image.Image:
    img = place(art, size, ADAPTIVE, Image.new("RGBA", (size, size), (0, 0, 0, 0)))
    if mono:  # themed icons only use the alpha channel
        black = Image.new("RGBA", img.size, (0, 0, 0, 255))
        black.putalpha(img.getchannel("A"))
        img = black
    return img


def main() -> None:
    art = aperture()
    full_icon(art, 1024).convert("RGB").save(BRAND / "app-icon-1024.png")
    # In-app logo (login, splash); Flutter rounds the corners itself.
    (ROOT / "assets" / "brand").mkdir(parents=True, exist_ok=True)
    full_icon(art, 384).convert("RGB").save(ROOT / "assets" / "brand" / "logo.png")

    res = ROOT / "android" / "app" / "src" / "main" / "res"
    for folder, px in {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}.items():
        out = res / f"mipmap-{folder}"
        full_icon(art, px, rounded=True).save(out / "ic_launcher.png")
        fg = px * 108 // 48  # adaptive layers are 108dp against a 48dp icon
        foreground(art, fg).save(out / "ic_launcher_foreground.png")
        foreground(art, fg, mono=True).save(out / "ic_launcher_monochrome.png")
    (res / "drawable").mkdir(exist_ok=True)
    (res / "drawable" / "ic_launcher_background.xml").write_text(f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/gen_app_icon.py. Dark gradient behind the aperture. -->
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <gradient android:angle="270"
        android:startColor="#{bytes(BG_TOP).hex().upper()}"
        android:endColor="#{bytes(BG_BOTTOM).hex().upper()}"/>
</shape>
""")
    (res / "mipmap-anydpi-v26").mkdir(exist_ok=True)
    (res / "mipmap-anydpi-v26" / "ic_launcher.xml").write_text("""<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
    <monochrome android:drawable="@mipmap/ic_launcher_monochrome"/>
</adaptive-icon>
""")
    (res / "values" / "ic_launcher_colors.xml").unlink(missing_ok=True)

    ios = ROOT / "ios" / "Runner" / "Assets.xcassets" / "AppIcon.appiconset"
    contents = json.loads((ios / "Contents.json").read_text())
    for image in contents["images"]:
        pts = float(image["size"].split("x")[0])
        px = round(pts * int(image["scale"].rstrip("x")))
        full_icon(art, px).convert("RGB").save(ios / image["filename"])  # iOS: square, no alpha
    print("icons written: design-system/brand, assets/brand/logo.png, Android mipmaps + adaptive, iOS AppIcon")


if __name__ == "__main__":
    main()
