// Usage: dart run tool/gen_tokens.dart  (run from app_flutter/)
// Reads ../design-system/tokens.json and writes lib/core/theme/tokens.g.dart
import 'dart:convert';
import 'dart:io';

late Map<String, dynamic> root;

dynamic resolve(dynamic v) {
  if (v is String && v.startsWith('{') && v.endsWith('}')) {
    dynamic cur = root;
    for (final k in v.substring(1, v.length - 1).split('.')) {
      cur = (cur as Map<String, dynamic>)[k];
    }
    return resolve((cur as Map<String, dynamic>)[r'$value']);
  }
  return v;
}

String camel(String s) {
  final parts = s.split(RegExp(r'[-_]'));
  return parts.first +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
}

String color(String hex) {
  var h = hex.replaceFirst('#', '').toUpperCase();
  if (h.length == 6) h = 'FF$h';
  return 'Color(0x$h)';
}

double dim(String v) => double.parse(v.replaceAll(RegExp(r'[a-z]+$'), ''));

void main() {
  root = jsonDecode(File('../design-system/tokens.json').readAsStringSync())
      as Map<String, dynamic>;
  final sem = root['semantic'] as Map<String, dynamic>;
  final semColors = sem['color'] as Map<String, dynamic>;
  final dark = ((root['dark'] as Map<String, dynamic>)['semantic']
      as Map<String, dynamic>)['color'] as Map<String, dynamic>;
  final prim = root['primitive'] as Map<String, dynamic>;
  final b = StringBuffer(
    '// GENERATED by tool/gen_tokens.dart from design-system/tokens.json. Do not edit.\n',
  )
    ..writeln("import 'package:flutter/material.dart';\n")
    ..writeln('class AppColors {\n  AppColors._();');
  for (final e in semColors.entries) {
    b.writeln(
      '  static const Color ${camel(e.key)} = ${color(resolve(e.value[r'$value']) as String)};',
    );
  }
  b.writeln('}\n\nclass AppColorsDark {\n  AppColorsDark._();');
  for (final e in semColors.entries) {
    final d = dark[e.key];
    b.writeln(
      d == null
          ? '  static const Color ${camel(e.key)} = AppColors.${camel(e.key)};'
          : '  static const Color ${camel(e.key)} = ${color(resolve(d[r'$value']) as String)};',
    );
  }
  b.writeln('}\n\nclass AppSpace {\n  AppSpace._();');
  for (final e in (prim['spacing'] as Map<String, dynamic>).entries) {
    b.writeln(
      '  static const double s${e.key} = ${dim(e.value[r'$value'] as String)};',
    );
  }
  b.writeln('}\n\nclass AppRadius {\n  AppRadius._();');
  for (final e in (prim['radius'] as Map<String, dynamic>).entries) {
    b.writeln(
      '  static const double ${camel(e.key)} = ${dim(e.value[r'$value'] as String)};',
    );
  }
  b.writeln('}\n\nclass AppText {\n  AppText._();');
  for (final e in (prim['fontSize'] as Map<String, dynamic>).entries) {
    final name = e.key == '2xl' ? 'xxl' : e.key;
    b.writeln(
      '  static const double $name = ${dim(e.value[r'$value'] as String)};',
    );
  }
  b.writeln('}\n\nclass AppFonts {\n  AppFonts._();');
  for (final e in (prim['font'] as Map<String, dynamic>).entries) {
    b.writeln("  static const String ${e.key} = '${e.value[r'$value']}';");
  }
  b.writeln('}');
  File('lib/core/theme/tokens.g.dart').writeAsStringSync(b.toString());
  stdout.writeln('wrote lib/core/theme/tokens.g.dart');
}
