#!/usr/bin/env python3
"""Land (merge) this machine's own plan PR into develop, but only when it is safe.

Gates, in order (each failing gate exits with its own code and a reason):
  1. the PR is open, targets develop, its head branch is the claimed branch,
     and its title is '<type>(<scope>): <summary> [<unit-id>]'  (exit 6: fix the title)
  2. the branch contains the latest origin/develop          (exit 2: rebase first)
  3. no file it changes is also changed by another machine's
     active claim branch, apart from the append-only files     (exit 4: wait / coordinate)
  4. every CI check on the PR passed (waits while pending)   (exit 3: fix the failure)
  5. GitHub reports the PR mergeable and not blocked         (exit 2 if behind/dirty,
                                                              exit 5 if blocked by rules)
Then: merge with a merge commit (house style), delete the branch, and mark
the claim done on the board.

Usage:
  land.py <unit-id> --pr <n>             run every gate, then merge
  land.py <unit-id> --pr <n> --dry-run   run the gates, do not merge
  land.py overlap --branch <b>           gate 3 only (no gh needed)

Never merges another machine's PR, never uses --admin, never touches main.
Env: same as board.py (BOARD_REMOTE, BOARD_BASE, BOARD_MACHINE, BOARD_GH=1).
"""
import argparse
import json
import os
import re
import subprocess
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import board  # noqa: E402

# Files several units may touch by design (append-only or regenerated); a
# rebase resolves them, so they never block a merge.
SHARED_OK = (
    "docs/superpowers/plans/RUN-ORDER.md",
    "app_flutter/lib/l10n/app_vi.arb",
    "app_flutter/lib/l10n/",            # generated by flutter gen-l10n
    "app_flutter/pubspec.lock",
)


TITLE = re.compile(r"^(feat|fix|refactor|perf|test|docs|chore|build|ci)\([a-z0-9-]+\): \S.{2,}\S \[[A-Za-z0-9./-]+\]$")


def git(*a, check=True):
    return board.sh("git", *a, check=check).stdout


def gh_json(*a):
    r = board.sh("gh", *a, check=False)
    if r.returncode != 0:
        sys.exit(f"error: gh {' '.join(a)}\n{r.stderr}")
    return json.loads(r.stdout or "null")


def changed(branch):
    ref = f"{board.REMOTE}/{branch}"
    if board.sh("git", "rev-parse", "-q", "--verify", ref, check=False).returncode != 0:
        return set()
    return set(git("diff", "--name-only", f"{board.REMOTE}/{board.BASE}...{ref}").split())


def shared_ok(path):
    return any(path == p or (p.endswith("/") and path.startswith(p)) for p in SHARED_OK)


def overlap(branch):
    """Files of `branch` also changed by other machines' active claim branches."""
    board.fetch()
    board.sh("git", *board.auth(), "fetch", "-q", board.target(),
             f"+refs/heads/plan/*:refs/remotes/{board.REMOTE}/plan/*", check=False)
    claims = board.parse(board.read_board(board.sh("git", "rev-parse", "-q", "--verify",
                         f"refs/remotes/{board.REMOTE}/{board.BRANCH}", check=False).stdout.strip() or None))
    mine = {p for p in changed(branch) if not shared_ok(p)}
    hits = {}
    for cid, c in claims.items():
        if c["branch"] == branch or not c["state"].startswith(board.ACTIVE):
            continue
        both = sorted(mine & changed(c["branch"]))
        if both:
            hits[f"{cid} ({c['machine']}, {c['branch']})"] = both
    return hits


def report_overlap(hits):
    for who, files in hits.items():
        print(f"overlap with {who}: {', '.join(files[:8])}{' …' if len(files) > 8 else ''}")


def cmd_overlap(a):
    hits = overlap(a.branch)
    if hits:
        report_overlap(hits)
        sys.exit(4)
    print("no overlap with other machines' active branches")


def cmd_land(a):
    me = board.machine()
    board.fetch()
    claim = board.parse(board.read_board(board.sh("git", "rev-parse", "-q", "--verify",
                        f"refs/remotes/{board.REMOTE}/{board.BRANCH}", check=False).stdout.strip() or None)).get(a.id)
    if not claim or claim["machine"] != me:
        sys.exit(f"error: {a.id} is not claimed by this machine ({me}); land only your own PR")
    pr = gh_json("pr", "view", a.pr, "--json", "state,baseRefName,headRefName,url")
    if pr["state"] != "OPEN" or pr["baseRefName"] != board.BASE or pr["headRefName"] != claim["branch"]:
        sys.exit(f"error: PR {a.pr} is {pr['state']} {pr['headRefName']} -> {pr['baseRefName']}; "
                 f"expected open {claim['branch']} -> {board.BASE}")
    title = gh_json("pr", "view", a.pr, "--json", "title")["title"]
    if not TITLE.match(title) or not title.endswith(f"[{a.id}]"):
        print(f"title does not follow the convention: {title!r}\n"
              f"expected '<type>(<scope>): <summary> [{a.id}]' (see SKILL.md 'PR title convention'); "
              f"fix with gh pr edit {a.pr} --title ...")
        sys.exit(6)
    branch = claim["branch"]
    board.sh("git", *board.auth(), "fetch", "-q", board.target(), f"+{branch}:refs/remotes/{board.REMOTE}/{branch}")

    # 2. up to date with develop
    if board.sh("git", "merge-base", "--is-ancestor", f"{board.REMOTE}/{board.BASE}",
                f"{board.REMOTE}/{branch}", check=False).returncode != 0:
        print(f"behind {board.BASE}: rebase onto origin/{board.BASE}, re-run the tests, push, then land again")
        sys.exit(2)

    # 3. no overlap with other machines' work in progress
    hits = overlap(branch)
    if hits:
        report_overlap(hits)
        print("not merging: another machine is changing the same files; see SKILL.md 'Landing'")
        sys.exit(4)

    # 4. CI checks (wait while pending, up to ~40 min)
    for _ in range(80):
        checks = gh_json("pr", "view", a.pr, "--json", "statusCheckRollup")["statusCheckRollup"] or []
        pending = [c for c in checks if (c.get("status") or "COMPLETED") != "COMPLETED"]
        failed = [c.get("name") or c.get("context") for c in checks
                  if (c.get("conclusion") or c.get("state") or "SUCCESS").upper()
                  not in ("SUCCESS", "NEUTRAL", "SKIPPED", "COMPLETED")]
        if failed and not pending:
            print(f"checks failed: {', '.join(failed)} (gh pr checks {a.pr})")
            sys.exit(3)
        if not pending:
            break
        time.sleep(30)
    else:
        print("checks still pending after 40 minutes; land again later")
        sys.exit(3)

    # 5. GitHub's own verdict
    for _ in range(10):
        st = gh_json("pr", "view", a.pr, "--json", "mergeable,mergeStateStatus")
        if st["mergeable"] != "UNKNOWN":
            break
        time.sleep(6)
    if st["mergeable"] == "CONFLICTING" or st["mergeStateStatus"] in ("BEHIND", "DIRTY"):
        print(f"GitHub says {st['mergeable']}/{st['mergeStateStatus']}: rebase onto origin/{board.BASE} and land again")
        sys.exit(2)
    if st["mergeStateStatus"] == "BLOCKED":
        print("blocked by branch rules (e.g. a required review): ask the user; never use --admin")
        sys.exit(5)

    if a.dry_run:
        print(f"all gates passed for PR {a.pr} ({st['mergeStateStatus']}); dry run, not merging")
        return
    r = board.sh("gh", "pr", "merge", a.pr, "--merge", "--delete-branch", check=False)
    if r.returncode != 0:
        print(f"merge refused: {r.stderr.strip()}")
        sys.exit(5)
    board.transact(lambda text: _done(text, a.id, a.pr), f"{a.id}: done (PR #{a.pr})")
    print(f"merged PR {a.pr} ({pr['url']}); {a.id} marked done")


def _done(text, cid, pr):
    claims = board.parse(text)
    c = claims.get(cid)
    if not c:
        return None
    c.update(state=f"done (PR #{pr})", date=board.today())
    return board.render(text, {k: v for k, v in claims.items() if k != cid}, (cid, c))


def main():
    if len(sys.argv) > 1 and sys.argv[1] == "overlap":
        p = argparse.ArgumentParser(); p.add_argument("cmd"); p.add_argument("--branch", required=True)
        return cmd_overlap(p.parse_args())
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("id"); p.add_argument("--pr", required=True); p.add_argument("--dry-run", action="store_true")
    cmd_land(p.parse_args())


if __name__ == "__main__":
    main()
