// GENERATED by tool/gen_tokens.dart from design-system/tokens.json. Do not edit.
import 'package:flutter/material.dart';

class AppColors {
  AppColors._();
  static const Color background = Color(0xFFF4F1EC);
  static const Color backgroundSubtle = Color(0xFFEDE9E3);
  static const Color surface = Color(0xFFFFFFFF);
  static const Color surfaceMuted = Color(0xFFEDE9E3);
  static const Color foreground = Color(0xFF313131);
  static const Color foregroundSecondary = Color(0xFF67625B);
  static const Color foregroundMuted = Color(0xFF898888);
  static const Color foregroundDisabled = Color(0xFFAEAEAE);
  static const Color foregroundInverse = Color(0xFFFFFFFF);
  static const Color primary = Color(0xFF8338F5);
  static const Color primaryPressed = Color(0xFF5B21B6);
  static const Color primarySubtle = Color(0xFFF4EEFF);
  static const Color primaryForeground = Color(0xFFFFFFFF);
  static const Color secondary = Color(0xFFEFEFEF);
  static const Color secondaryPressed = Color(0xFFE9E9E9);
  static const Color secondaryForeground = Color(0xFF313131);
  static const Color destructive = Color(0xFFE91E11);
  static const Color destructivePressed = Color(0xFFB21D14);
  static const Color destructiveForeground = Color(0xFFFFFFFF);
  static const Color success = Color(0xFF1A9F02);
  static const Color successSubtle = Color(0xFFE3F5DF);
  static const Color warning = Color(0xFFE6C617);
  static const Color warningSubtle = Color(0xFFFBF6DA);
  static const Color error = Color(0xFFE91E11);
  static const Color errorSubtle = Color(0xFFFCE4E2);
  static const Color info = Color(0xFF8338F5);
  static const Color infoSubtle = Color(0xFFF4EEFF);
  static const Color border = Color(0xFFE3DFD8);
  static const Color borderStrong = Color(0xFFCFCAC1);
  static const Color divider = Color(0xFFE3DFD8);
  static const Color focusRing = Color(0xFF8338F5);
  static const Color overlay = Color(0x6A000000);
  static const Color overlayLight = Color(0x88FFFFFF);
  static const Color rating = Color(0xFFE6C617);
  static const Color bookingWaiting = Color(0xFF8338F5);
  static const Color bookingAccepted = Color(0xFF1A9F02);
  static const Color bookingDenied = Color(0xFFB21D14);
  static const Color bookingOpened = Color(0xFFE6C617);
  static const Color bookingClosed = Color(0xFF898888);
  static const Color heroCanvas = Color(0xFF0B0B10);
  static const Color ctaStart = Color(0xFF3D63FF);
  static const Color ctaMid = Color(0xFF8A3FFC);
  static const Color ctaEnd = Color(0xFFD6249F);
  static const Color ctaLightStart = Color(0xFF8338F5);
  static const Color ctaLightEnd = Color(0xFF702BDB);
  static const Color spectrumCyan = Color(0xFF14E0F5);
  static const Color spectrumViolet = Color(0xFF8A3FFC);
  static const Color spectrumPink = Color(0xFFFF45D0);
  static const Color spectrumOrange = Color(0xFFFF8A4C);
  static const Color spectrumYellow = Color(0xFFFFD54A);
}

class AppColorsDark {
  AppColorsDark._();
  static const Color background = Color(0xFF0B0B10);
  static const Color backgroundSubtle = Color(0xFF13121A);
  static const Color surface = Color(0xFF17151F);
  static const Color surfaceMuted = Color(0x14FFFFFF);
  static const Color foreground = Color(0xFFF7F7F7);
  static const Color foregroundSecondary = Color(0xFFD6D6D6);
  static const Color foregroundMuted = Color(0xFFAEAEAE);
  static const Color foregroundDisabled = Color(0xFF707070);
  static const Color foregroundInverse = AppColors.foregroundInverse;
  static const Color primary = Color(0xFFB08AFF);
  static const Color primaryPressed = Color(0xFFCDB4FF);
  static const Color primarySubtle = Color(0xFF2C0F5C);
  static const Color primaryForeground = Color(0xFF0B0B10);
  static const Color secondary = Color(0x14FFFFFF);
  static const Color secondaryPressed = Color(0x24FFFFFF);
  static const Color secondaryForeground = Color(0xFFF7F7F7);
  static const Color destructive = AppColors.destructive;
  static const Color destructivePressed = AppColors.destructivePressed;
  static const Color destructiveForeground = AppColors.destructiveForeground;
  static const Color success = AppColors.success;
  static const Color successSubtle = AppColors.successSubtle;
  static const Color warning = AppColors.warning;
  static const Color warningSubtle = AppColors.warningSubtle;
  static const Color error = AppColors.error;
  static const Color errorSubtle = AppColors.errorSubtle;
  static const Color info = AppColors.info;
  static const Color infoSubtle = AppColors.infoSubtle;
  static const Color border = Color(0x1FFFFFFF);
  static const Color borderStrong = Color(0x33FFFFFF);
  static const Color divider = Color(0x1FFFFFFF);
  static const Color focusRing = Color(0xFF14E0F5);
  static const Color overlay = AppColors.overlay;
  static const Color overlayLight = AppColors.overlayLight;
  static const Color rating = AppColors.rating;
  static const Color bookingWaiting = AppColors.bookingWaiting;
  static const Color bookingAccepted = AppColors.bookingAccepted;
  static const Color bookingDenied = AppColors.bookingDenied;
  static const Color bookingOpened = AppColors.bookingOpened;
  static const Color bookingClosed = AppColors.bookingClosed;
  static const Color heroCanvas = AppColors.heroCanvas;
  static const Color ctaStart = AppColors.ctaStart;
  static const Color ctaMid = AppColors.ctaMid;
  static const Color ctaEnd = AppColors.ctaEnd;
  static const Color ctaLightStart = AppColors.ctaLightStart;
  static const Color ctaLightEnd = AppColors.ctaLightEnd;
  static const Color spectrumCyan = AppColors.spectrumCyan;
  static const Color spectrumViolet = AppColors.spectrumViolet;
  static const Color spectrumPink = AppColors.spectrumPink;
  static const Color spectrumOrange = AppColors.spectrumOrange;
  static const Color spectrumYellow = AppColors.spectrumYellow;
}

class AppSpace {
  AppSpace._();
  static const double s0 = 0.0;
  static const double s1 = 4.0;
  static const double s2 = 8.0;
  static const double s3 = 12.0;
  static const double s4 = 16.0;
  static const double s5 = 20.0;
  static const double s6 = 24.0;
  static const double s8 = 32.0;
  static const double s10 = 40.0;
  static const double s12 = 48.0;
  static const double s16 = 64.0;
}

class AppRadius {
  AppRadius._();
  static const double none = 0.0;
  static const double sm = 4.0;
  static const double md = 8.0;
  static const double lg = 12.0;
  static const double control = 14.0;
  static const double xl = 16.0;
  static const double card = 20.0;
  static const double sheet = 28.0;
  static const double full = 999.0;
}

class AppText {
  AppText._();
  static const double xs = 10.0;
  static const double xs2 = 11.0;
  static const double sm = 12.0;
  static const double base2 = 13.5;
  static const double base = 14.0;
  static const double md = 16.0;
  static const double lg = 20.0;
  static const double xl = 24.0;
  static const double xxl = 35.0;
}

class AppFonts {
  AppFonts._();
  static const String display = 'Fraunces';
  static const String body = 'Be Vietnam Pro';
}
